# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d8b65d573892701af9bb288783b19dcad9ded43f7f25b2798fb80ef9133b676bb60ed332d3df6e77946b5131e737f4cedb297a4fdb85909c51932b631a83aed

test:
  secret_key_base: 27475c72ddc800fd32e653276561f59521bac696b7e21c5891bb53e53a8849be6e43b6e86038ee650af29772d3dcdc2126c13cfd3ee5ab57862cbd1b37dc193b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
